# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12faba14c480f9af14b4289fa973ba36c0c026beb959a1753e261bfef37518d9380907e545c6493a665cf5ba6d0e9f2cbd3c81c8c64422194f5547ba46c55fb3

test:
  secret_key_base: 15f8304f4431f92c9084ddd896c5af69c43af3ea4da15ed9742d1102e209cbe22481e6683525d282408f3a15643e89c23086d35db5b0d8629f5e3a21f08d06ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
